apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: baron-capital-ingress
  namespace: baron-capital
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - baroncapital.co.ke
      secretName: baron-capital-tls
  rules:
    - host: baroncapital.co.ke
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-core
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
