# Generated by Django 5.0.7 on 2026-09-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.PositiveIntegerField(help_text='References core_app.LoanApplication.id')),
                ('id_document_verified', models.BooleanField(default=False)),
                ('aml_screening_result', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('flagged', 'Flagged for Review'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
